/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Parameters for scanning a block range for shielded transactions.
 *
 * The UFVK must be obtained from the Ledger device — never derive it from
 * a seed phrase directly in this layer.
 */
export interface SyncParams {
  /** gRPC endpoint URL (e.g. `"https://testnet.zec.rocks:443"`). */
  grpcUrl: string
  /** Unified Full Viewing Key (UFVK) for the account to scan. */
  viewingKey: string
  /** First block height to scan (inclusive). */
  startHeight: number
  /** Last block height to scan (inclusive). */
  endHeight: number
  /** `"mainnet"` or `"testnet"` (default: `"testnet"`). */
  network?: string
  /**
   * When `true`, Sapling outputs are stripped before trial decryption.
   * Only Orchard actions are processed — eliminates all Sapling crypto work.
   * Set to `true` for Ledger wallets (Orchard-only support).
   */
  orchardOnly?: boolean
  /**
   * Maximum retry attempts per range on transient errors (timeout, 503).
   * The failing range is split in half on each retry. Defaults to 3.
   */
  maxRetries?: number
}
/** A single shielded note found during decryption. */
export interface ShieldedNote {
  /** Amount in zatoshis (f64 for JS Number compatibility). */
  amount: number
  /** `"incoming"`, `"outgoing"`, or `"internal"`. */
  transferType: string
  /** Memo text decoded from the note. */
  memo: string
}
/** A matched and fully-decrypted shielded transaction. */
export interface ShieldedTransaction {
  /** Transaction ID in big-endian (display) hex order. */
  txid: string
  /** Raw transaction bytes as a hex string. */
  hex: string
  /** Block height at which this transaction was confirmed. */
  blockHeight: number
  /** Block hash in big-endian (display) hex order. */
  blockHash: string
  /** Block timestamp (Unix seconds). */
  blockTime: number
  /** Transaction fee in zatoshis (shielded bundles only). */
  fee: number
  /** Decrypted Sapling notes belonging to this account. */
  saplingNotes: Array<ShieldedNote>
  /** Decrypted Orchard notes belonging to this account. */
  orchardNotes: Array<ShieldedNote>
}
/** Scan statistics returned once the stream is exhausted. */
export interface SyncStats {
  blocksScanned: number
  elapsedMs: number
}
/**
 * Start scanning a range of compact blocks and return a transaction stream.
 *
 * The scan runs in the background immediately. Call `stream.next()` to
 * consume transactions as they are found. Call `stream.stats()` after the
 * stream is exhausted to retrieve scan statistics.
 *
 * Trial decryption runs entirely in Rust (no JS event loop blocking).
 * `GetTransaction` is called only for matched transactions.
 */
export declare function startSync(params: SyncParams): Promise<TransactionStream>
/** Returns the current chain tip height from the gRPC endpoint. */
export declare function getChainTip(grpcUrl: string): Promise<number>
/**
 * Async iterator over matched shielded transactions.
 *
 * Usage (TypeScript):
 * ```ts
 * const stream = await startSync(params);
 * let tx: ShieldedTransaction | null;
 * while ((tx = await stream.next()) !== null) {
 *   console.log(tx);
 * }
 * const stats = await stream.stats();
 * ```
 */
export declare class TransactionStream {
  /**
   * Returns the next matched transaction, or `null` when the scan is complete.
   *
   * Safety: napi-rs requires `unsafe` for `&mut self` in async methods.
   * This method is safe to call — it only mutates the internal channel receiver.
   */
  next(): Promise<ShieldedTransaction | null>
  /**
   * Returns scan statistics once the stream is exhausted (i.e. after `next()`
   * returns `null`). Calling this before the stream is done will wait until
   * the background sync task finishes.
   *
   * Safety: napi-rs requires `unsafe` for `&mut self` in async methods.
   */
  stats(): Promise<SyncStats>
}
