/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parameters for deriving Zcash viewing keys from a BIP-39 mnemonic. */
export interface DeriveKeysParams {
  /** BIP-39 mnemonic phrase (12 or 24 words). */
  mnemonic: string
  /** ZIP-32 account index (default: 0). */
  account: number
  /** `"mainnet"` or `"testnet"` (default: `"mainnet"`). */
  network?: string
  /** Custom BIP-32 xpub derivation path (default: `m/44'/133'/{account}'`). */
  xpubPath?: string
  /** Whether to include the Sapling FVK inside the generated UFVK (default: true). */
  includeSaplingInUfvk?: boolean
}
/** Viewing keys for a single shielded pool. */
export interface PoolViewingKeys {
  fvk: string
  ivk: string
  ovk: string
}
/** All keys derived from a BIP-39 mnemonic for a Zcash account. */
export interface DerivedKeys {
  /** Bech32m Unified Full Viewing Key (HRP `"uview1"` / `"uviewtest1"`). */
  ufvk: string
  /** BIP-32 transparent extended public key (Base58Check). */
  xpub: string
  /** BIP-32 path used for xpub derivation. */
  xpubPath: string
  /** Sapling pool viewing keys. */
  sapling?: PoolViewingKeys
  /** Orchard pool viewing keys. */
  orchard?: PoolViewingKeys
}
/** Parameters for scanning a block range for shielded transactions. */
export interface SyncParams {
  /** gRPC endpoint URL (e.g. `"https://testnet.zec.rocks:443"`). */
  grpcUrl: string
  /** Unified Full Viewing Key (UFVK) for the account to scan. */
  viewingKey: string
  /** First block height to scan (inclusive). */
  startHeight: number
  /** Last block height to scan (inclusive). */
  endHeight: number
  /** `"mainnet"` or `"testnet"` (default: `"testnet"`). */
  network?: string
}
/** A single shielded note found during decryption. */
export interface ShieldedNote {
  /** Amount in zatoshis (f64 for JS Number compatibility). */
  amount: number
  /** `"incoming"`, `"outgoing"`, or `"internal"`. */
  transferType: string
  /** Memo text decoded from the note. */
  memo: string
}
/** A matched and fully-decrypted shielded transaction. */
export interface ShieldedTransaction {
  /** Transaction ID in big-endian (display) hex order. */
  txid: string
  /** Raw transaction bytes as a hex string. */
  hex: string
  /** Block height at which this transaction was confirmed. */
  blockHeight: number
  /** Block hash in big-endian (display) hex order. */
  blockHash: string
  /** Block timestamp (Unix seconds). */
  blockTime: number
  /**
   * Transaction fee in zatoshis (= valueBalanceSapling + valueBalanceOrchard).
   * Always ≥ 0 for valid fully-shielded transactions.
   */
  fee: number
  /** Decrypted Sapling notes belonging to this account. */
  saplingNotes: Array<ShieldedNote>
  /** Decrypted Orchard notes belonging to this account. */
  orchardNotes: Array<ShieldedNote>
}
/** Result returned after scanning a block range. */
export interface SyncResult {
  transactions: Array<ShieldedTransaction>
  blocksScanned: number
  elapsedMs: number
}
/**
 * Derive all Zcash viewing keys from a BIP-39 mnemonic.
 *
 * Returns UFVK, xpub, and per-pool (Sapling + Orchard) viewing keys.
 *
 * This is a CPU-bound synchronous operation — it does not require a gRPC connection.
 */
export declare function deriveKeys(params: DeriveKeysParams): DerivedKeys
/**
 * Scan a range of Zcash compact blocks for shielded transactions matching the given UFVK.
 *
 * Uses gRPC `GetBlockRange` streaming for maximum throughput. Trial decryption runs
 * entirely in Rust (no JS event loop blocking). `GetTransaction` is called only for
 * matched transactions, minimising bandwidth.
 */
export declare function syncShielded(params: SyncParams): Promise<SyncResult>
/** Returns the current chain tip height from the gRPC endpoint. */
export declare function getChainTip(grpcUrl: string): Promise<number>
